config/routes.rb
Rails.application.routes.draw do
  get 'game', to: 'pages#game'

  post 'score', to: 'pages#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
require 'open-uri'

class PagesController < ApplicationController
  def game
    @grid = generate_grid(8)
    @start_time = Time.now
  end

  def score
    @guess = params[:guess]
    start_time = Time.parse(params[:start_time])
    end_time = Time.now
    grid = params[:grid].split(",")

    # calling the methods
    @result = run_game(@guess, grid, start_time, end_time)
  end

  private

  def generate_grid(grid_size)
    Array.new(grid_size) { ('A'..'Z').to_a.sample }
  end

  def included?(guess, grid)
    guess.chars.all? { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def compute_score(attempt, time_taken)
    time_taken > 60.0 ? 0 : attempt.size * (1.0 - time_taken / 60.0)
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: end_time - start_time }

    score_and_message = score_and_message(attempt, grid, result[:time])
    result[:score] = score_and_message.first
    result[:message] = score_and_message.last

    return result
  end

  def score_and_message(attempt, grid, time)
    if included?(attempt.upcase, grid)
      if english_word?(attempt)
        score = compute_score(attempt, time)
        [score, "well done"]
      else
        [0, "not an english word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def english_word?(word)
    response = open("https://wagon-dictionary.herokuapp.com/#{word}")
    json = JSON.parse(response.read)
    return json['found']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style = "background-color: rgb(240, 240, 240)">
    <%= yield %>
  </body>
</html>

app/views/pages/game.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4">
      <h1>Game</h1>
      <p>Welcome to the longest game in the world!</p>

      <h3><%= @grid.join(" ")%></h3>

      <form action="score" method="post" class="form-inline">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="text" name="guess" placeholder="Take your chance" class="form-control">
        <input type="hidden" name="start_time" value="<%= @start_time %>">
        <input type="hidden" name="grid" value="<%= @grid.join(',') %>">
        <input type="submit" value="Go!" class="btn btn-primary ">
      </form>
    </div>
  </div>
</div>

app/views/pages/score.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4">
      <h1>Score</h1>

      <h3>YOUR GUESS: <%= @guess %> </h3>
      <h4>Time taken: <%= @result[:time] %></h4>
      <h4>Your socre: <%= @result[:score] %></h4>
      <h4>Message: <%= @result[:message]%></h4>

      <%= link_to 'Play again!', game_path %>
    </div>
  </div>
</div>